2025-09-04 13:02:50,315 - INFO - User registered successfully: esh@example.com
2025-09-04 13:09:30,471 - INFO - User registered successfully: akhi@example.com
2025-09-04 13:12:56,437 - WARNING - Registration failed: User already exists - ram@example.com
2025-09-04 13:13:43,484 - INFO - User registered successfully: ram@example.com
2025-09-04 14:22:43,324 - INFO - User logged in successfully: john@example.com
2025-09-04 14:25:19,133 - WARNING - Login failed: Incorrect password - john@example.com
2025-09-04 14:26:45,204 - INFO - User logged in successfully: john@example.com
2025-09-04 15:09:57,103 - INFO - Team created successfully: Warriors
2025-09-04 15:10:59,336 - INFO - Team created successfully: Thunders
2025-09-04 15:12:00,889 - INFO - Team created successfully: Rangers
2025-09-04 15:16:13,308 - WARNING - Team creation failed: Rangers already exists
2025-09-04 15:29:44,571 - INFO - Fetched all teams
2025-09-04 15:31:13,063 - INFO - Fetched all teams
2025-09-04 15:33:03,901 - INFO - Fetched all teams
2025-09-04 15:34:32,286 - INFO - Fetched all teams
2025-09-04 15:47:03,556 - INFO - Fetched all teams
2025-09-04 15:48:06,012 - INFO - Fetched all teams
2025-09-04 15:48:13,080 - INFO - Fetched all teams
2025-09-04 15:48:18,012 - INFO - Fetched all teams
2025-09-04 15:48:21,371 - INFO - Fetched all teams
2025-09-04 15:49:34,637 - INFO - Fetched all teams
2025-09-04 15:49:38,476 - INFO - Fetched all teams
2025-09-04 17:19:31,050 - INFO - User logged in successfully: esh@example.com
2025-09-04 17:26:18,124 - INFO - User logged in successfully: esh@example.com
2025-09-04 17:45:22,550 - INFO - User logged in successfully: esh@example.com
2025-09-04 17:46:48,956 - INFO - Team created successfully: Challengers
2025-09-04 17:48:49,567 - INFO - Team created successfully: Royel Challengers
2025-09-04 17:49:40,016 - ERROR - Invalid or expired token
Traceback (most recent call last):
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jws.py", line 189, in _load
    header = json.loads(header_data.decode("utf-8"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 6: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 159, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jws.py", line 74, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jws.py", line 191, in _load
    raise JWSError("Invalid header string: %s" % e)
jose.exceptions.JWSError: Invalid header string: 'utf-8' codec can't decode byte 0x88 in position 6: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\auth.py", line 14, in get_current_user
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 161, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Invalid header string: 'utf-8' codec can't decode byte 0x88 in position 6: invalid start byte
2025-09-04 17:49:51,917 - WARNING - Team creation failed: Royel Challengers already exists
2025-09-05 00:10:58,307 - INFO - User logged in successfully: esh@example.com
2025-09-05 00:11:36,487 - INFO - User logged in successfully: esh@example.com
2025-09-05 00:14:31,850 - INFO - User esh@example.com fetched all teams
2025-09-05 00:18:10,864 - INFO - Player created successfully: Stephen Curry
2025-09-05 00:18:37,619 - INFO - Player created successfully: Stephen Curry
2025-09-05 00:19:48,217 - INFO - Player created successfully: Jhohan
2025-09-05 00:21:41,676 - INFO - Player created successfully: Jack
2025-09-05 00:23:19,246 - INFO - Player created successfully: Jhon Snow
2025-09-05 00:24:21,465 - INFO - Player created successfully: Jhonathan
2025-09-05 00:25:59,640 - INFO - Player created successfully: Arjun
2025-09-05 00:26:11,693 - ERROR - Unexpected error during player creation: '68b983300b1bcd47ca36083' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\routes\player_routes.py", line 21, in create_player
    if not teams_collection.find_one({"_id": ObjectId(player.team_id)}):
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\bson\objectid.py", line 105, in __init__
    self.__validate(oid)
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\bson\objectid.py", line 193, in __validate
    _raise_invalid_id(oid)
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\bson\objectid.py", line 38, in _raise_invalid_id
    raise InvalidId(
bson.errors.InvalidId: '68b983300b1bcd47ca36083' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2025-09-05 00:26:34,363 - INFO - Player created successfully: Arjun
2025-09-05 00:40:22,417 - INFO - User esh@example.com fetched all players
2025-09-05 00:40:30,112 - INFO - User esh@example.com fetched all players
2025-09-05 13:27:33,869 - INFO - User logged in successfully: esh@example.com
2025-09-05 13:28:07,404 - INFO - User esh@example.com fetched all teams
2025-09-05 13:35:12,691 - INFO - Match scheduled: Warriors vs Royel Challengers on 2025-09-10 18:30
2025-09-05 13:36:58,286 - INFO - Match scheduled: Royel Challengers vs Warriors on 2025-10-15 20:30
2025-09-05 13:38:28,562 - INFO - Match scheduled: Royel Challengers vs Challengers on 2025-9-25 20:30
2025-09-05 13:40:09,335 - WARNING - A team cannot play against itself
2025-09-05 13:51:36,390 - INFO - User esh@example.com fetched all matches
2025-09-05 13:52:02,008 - INFO - User esh@example.com fetched all matches
2025-09-05 17:36:45,112 - INFO - User logged in successfully: esh@example.com
2025-09-05 17:37:23,643 - INFO - User esh@example.com fetched all players
2025-09-05 17:40:42,874 - INFO - User esh@example.com fetched player Jack
2025-09-30 12:49:44,346 - INFO - User registered successfully: ram@example.com
2025-09-30 12:49:59,540 - INFO - User logged in successfully: esh@example.com
2025-09-30 12:51:39,738 - INFO - Team created successfully: Royel Challengers
2025-09-30 12:52:04,942 - ERROR - Invalid or expired token
Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\auth.py", line 13, in get_current_user
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
2025-09-30 13:11:16,582 - ERROR - Invalid or expired token
Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\auth.py", line 13, in get_current_user
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
2025-09-30 13:11:38,479 - INFO - Player created successfully: Arjun
2025-09-30 13:11:44,505 - ERROR - Invalid or expired token
Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\auth.py", line 13, in get_current_user
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
2025-09-30 13:12:08,574 - WARNING - One or both teams not found
2025-09-30 13:13:21,722 - WARNING - One or both teams not found
2025-09-30 13:13:51,630 - INFO - Match scheduled: Warriors vs Thunders on 2025-9-27 20:30
2025-09-30 13:14:08,048 - ERROR - Invalid or expired token
Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\auth.py", line 13, in get_current_user
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.
2025-09-30 13:14:20,184 - ERROR - Invalid or expired token
Traceback (most recent call last):
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jws.py", line 180, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 159, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jws.py", line 74, in verify
    header, payload, signing_input, signature = _load(token)
                                                ^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jws.py", line 184, in _load
    raise JWSError("Not enough segments")
jose.exceptions.JWSError: Not enough segments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Gameplan\GamePlan-Sports-Team-Match-Scheduling-API\app\auth.py", line 13, in get_current_user
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K K\anaconda3\envs\gameplan\Lib\site-packages\jose\jwt.py", line 161, in decode
    raise JWTError(e)
jose.exceptions.JWTError: Not enough segments
2025-09-30 13:14:49,662 - INFO - User esh@example.com fetched all matches
2025-09-30 13:15:19,828 - INFO - User esh@example.com fetched player Jack
